# """
# Generates a daily summary of the entire parent project
# """

# import os
# import json
# import requests
# from datetime import datetime, timedelta

# def generate_daily_summary():
#     # Navigate to parent project
#     project_root = "../../"
#     os.chdir(project_root)
    
#     # Get project statistics
#     stats = {
#         'total_files': 0,
#         'total_size_mb': 0,
#         'by_extension': {},
#         'recent_changes': [],
#         'folder_structure': {}
#     }
    
#     # Walk through project
#     for root, dirs, files in os.walk('.'):
#         # Skip hidden folders and product-documenter's internal files
#         dirs[:] = [d for d in dirs if not d.startswith('.') and d != '__pycache__']
#         if 'product-documenter' in root and 'product-documenter/docs' not in root:
#             continue
        
#         rel_root = os.path.relpath(root, '.')
        
#         for file in files:
#             if file.startswith('.'):
#                 continue
                
#             filepath = os.path.join(root, file)
#             stats['total_files'] += 1
            
#             # Get file stats
#             try:
#                 size = os.path.getsize(filepath)
#                 stats['total_size_mb'] += size / (1024 * 1024)
                
#                 # Track by extension
#                 ext = os.path.splitext(file)[1].lower()
#                 stats['by_extension'][ext] = stats['by_extension'].get(ext, 0) + 1
                
#                 # Check if modified recently (last 24h)
#                 mtime = datetime.fromtimestamp(os.path.getmtime(filepath))
#                 if datetime.now() - mtime < timedelta(hours=24):
#                     stats['recent_changes'].append({
#                         'file': filepath[2:],  # Remove './'
#                         'modified': mtime.strftime('%H:%M'),
#                         'size_kb': round(size / 1024, 2)
#                     })
                    
#             except:
#                 continue
    
#     # Get Git status if available
#     git_status = ""
#     try:
#         import subprocess
#         git_result = subprocess.run(['git', 'status', '--short'], 
#                                   capture_output=True, text=True)
#         if git_result.returncode == 0:
#             git_status = git_result.stdout.strip()
#     except:
#         pass
    
#     # Create comprehensive context
#     context = f"""
# # DAILY PROJECT SUMMARY
# ## Almond Milk Homogenization Repository
# ### {datetime.now().strftime('%Y-%m-%d')}

# ## 📊 Project Statistics
# - **Total Files**: {stats['total_files']:,}
# - **Total Size**: {stats['total_size_mb']:.2f} MB
# - **Main File Types**: {', '.join([f'{k} ({v})' for k, v in sorted(stats['by_extension'].items(), key=lambda x: x[1], reverse=True)[:5]])}

# ## 🔄 Recent Activity (Last 24h)
# {f"• {change['file']} ({change['modified']}, {change['size_kb']}KB)" for change in sorted(stats['recent_changes'], key=lambda x: x['modified'], reverse=True)[:10] if change['file'] and not 'product-documenter/scripts' in change['file']}

# {f'... and {len(stats['recent_changes'])-10} more' if len(stats['recent_changes']) > 10 else ''}

# ## 🏗️ Project Structure
# {get_folder_tree('.', max_depth=3)}


# ## 🎯 Focus Areas Today
# Based on recent activity, focus on:
# 1. {suggest_focus_area(stats)}
# 2. {suggest_focus_area(stats, rank=2)}
# 3. {suggest_focus_area(stats, rank=3)}

# ## 📈 Progress Metrics
# - Documentation coverage: {calculate_doc_coverage()}%
# - Test coverage: {calculate_test_coverage()}%
# - Code quality score: {calculate_quality_score()}/10

# ---

# *This daily summary was auto-generated by the Product Documenter AI Agent.*
# """
    
#     # Send to documenter
#     payload = {
#         'context': context,
#         'doc_type': 'daily_summary',
#         'licensing_focus': False,
#         'source': 'daily_summary',
#         'metadata': {
#             'summary_date': datetime.now().isoformat(),
#             'file_stats': stats,
#             'git_available': bool(git_status)
#         }
#     }
    
#     try:
#         # Go back to product-documenter scripts
#         os.chdir("product-documenter/scripts")
        
#         response = requests.post("http://localhost:8000/generate", 
#                                json=payload, timeout=30)
        
#         if response.status_code == 200:
#             print(f"✅ Daily summary generated for {datetime.now().date()}")
#             return True
#         else:
#             print(f"⚠️  Failed: {response.status_code}")
#             return False
            
#     except Exception as e:
#         print(f"❌ Error: {e}")
#         return False

# def get_folder_tree(root, max_depth=3, prefix=""):
#     """Generate a folder tree structure"""
#     result = []
    
#     # Get visible directories
#     items = [d for d in os.listdir(root) 
#              if not d.startswith('.') and 
#              d != '__pycache__' and
#              not (root == '.' and d == 'product-documenter')]
#     items.sort()
    
#     for i, item in enumerate(items):
#         path = os.path.join(root, item)
#         is_last = (i == len(items) - 1)
        
#         if os.path.isdir(path):
#             result.append(f"{prefix}{'└── ' if is_last else '├── '}{item}/")
#             if max_depth > 1:
#                 extension = "    " if is_last else "│   "
#                 result.append(get_folder_tree(path, max_depth-1, prefix + extension))
#         else:
#             result.append(f"{prefix}{'└── ' if is_last else '├── '}{item}")
    
#     return "\n".join(result)

# def suggest_focus_area(stats, rank=1):
#     """Suggest focus areas based on project stats"""
#     if rank == 1:
#         return "Core homogenization algorithms"
#     elif rank == 2:
#         return "Sensor data processing modules"
#     else:
#         return "Documentation and testing"

# def calculate_doc_coverage():
#     """Calculate documentation coverage percentage"""
#     return 65  # Placeholder - implement real calculation

# def calculate_test_coverage():
#     """Calculate test coverage percentage"""
#     return 72  # Placeholder

# def calculate_quality_score():
#     """Calculate code quality score"""
#     return 8  # Placeholder

# if __name__ == "__main__":
#     generate_daily_summary()